import "./globals.css";
import { Comforter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const comforter = Comforter({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={comforter.className}>
        {/* 字体颜色为白色 */}
        {children}
      </body>
    </html>
  );
}
